server.port=8086
spring.application.name=auth-service

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/eureka_auth_db

spring.datasource.username=postgres
spring.datasource.password=holdontohope
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# JWT
jwt.secret=sfgrcr66876o5p4krm4fi2o3k4tm45io6p543krxm34t3

# 14 days: 14 * 24 * 60 * 60 * 1000 = 1209600000
jwt.expiration=1209600000

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
