management.cors.allow_origins.1 = http://localhost:3000
management.cors.allow_methods.1 = GET, OPTIONS
management.cors.allow_headers.1 = authorization, content-type
management.cors.allow_credentials = true